### ISSUE TITLE
Implement an endpoint for submitting a vote towards a specific server

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/announce-backend#13]
Some more thought should be put into the mitigation of abuse of this.

This will probably require a recaptcha and other methods to prevent abuse.

**Comment by BigETI** [comment]
I know this from Minecraft server lists, that you can obtain vote statistics. So you can for example reward your players by letting them vote for your server.

**Comment by BigETI** [comment]
And we need an endpoint to obtain the servers sorted by daily, weekly or monthly votes.

**Comment by Southclaws** [comment]
I plan to at some point implement a rank value that will be calculated from various metrics and I'll integrate votes into that calculation.
