### ISSUE TITLE
Handle server outages without deleting the server permanently

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/announce-backend#14]
Right now, if a server fails a query x times, it is deleted permanently.

Currently, x is 100 and queries happen every minute so if a server is offline for 100 minutes, it's removed.

This is not ideal. A server could go offline for a day or more due to maintenance or technical issues.

The solution to this would be to mark a server as "inactive" to hide it from search results and place it in a pool which queries it less often (4x normal query time for example) so as to not waste resources - similar to the "exponential-backoff" pattern.

**Comment by BigETI** [comment]
If the POST request are automated, it shouldn't be a problem. However that is not ideal, if you only rely on adding your server manually.
