### ISSUE TITLE
Add character page guessing based on country of origin and text analysis

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/announce-backend#19]
https://godoc.org/golang.org/x/text/encoding/charmap

Tokenising the hostname then doing a dictionary lookup could also be a good way to determine the name. There are lots of common words used in hostnames. Needs research.

First iteration of this can be done with IP geo locations.

**Comment by BigETI** [comment]
Add an option to send the appropriate charset string, which is already stated here: https://github.com/Southclaws/announce-backend/issues/4

**Comment by BigETI** [comment]
This is a documentation of the windows codepages: https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx

**Comment by Southclaws** [comment]
already added to #11 for v2, this issue is a separate feature that will be implemented in v3

**Comment by Southclaws** [comment]
https://github.com/saintfish/chardet
