### ISSUE TITLE
Connection refused on almost all servers - probably related to the recent update

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/announce-backend#23]
I'll have to dig into the changes of the query API in the recent bug fix release of the SA:MP server package.

**Comment by Bios-Marcel** [comment]
I have noticed problems aswell, but only on a small amount of specific servers

**Comment by Bios-Marcel** [comment]
Would be great if you report the knowledge you are gaining

**Comment by BigETI** [comment]
My implementation of the SA:MP query mechanism has no issues querying servers whatsoever. What I've seen is that you're software is not utilizing the `p` query.
http://wiki.sa-mp.com/wiki/Query#Opcodes

@Bios-Marcel this is how not to utilize the `p` query: https://github.com/Bios-Marcel/ServerBrowser/blob/8c8c5f86bc243720c250305b7ab5693c83a7df04/client/src/main/java/com/msc/serverbrowser/util/samp/SampQuery.java#L33

**Comment by BigETI** [comment]
Take a look at https://github.com/BigETI/SAMPLauncherNET/blob/master/SAMPLauncherNET/Server.cs#L782 and https://github.com/BigETI/SAMPLauncherNET/blob/master/SAMPLauncherNET/Server.cs#L823

**Comment by Bios-Marcel** [comment]
the p query isn't the problem though

**Comment by BigETI** [comment]
The changes are related to the `p` query.

**Comment by Southclaws** [comment]
I think I've resolved this in v2 now, gonna deploy so update your endpoints to use `v2` instead of `v1`.

**Comment by Southclaws** [comment]
Seems to be resolved now
