### ISSUE TITLE
Offline servers are still shown

### ISSUE THREAD

**Issue by Bios-Marcel** [Southclaws/announce-backend#29]
Offline servers should either not show (after online for a longer while) or at least its playercount should be cleared.

So when retrieving the server you see `YYYY/XXXX` players, but infact the server is offline, that makes no sense.

**Comment by Southclaws** [comment]
Offline servers should not be listed at all, I'll look into this when I get time.

**Comment by Bios-Marcel** [comment]
Over 1300 over the listed servers are not online.

I queried the whole list with a timeout of 2000ms to make sure they aren't just lagging.

**Comment by Southclaws** [comment]
The list consists of servers queried from the official list about a month ago so it amazes me how so many servers were shortly lived!

I'll get on a fix for this soon.
