### ISSUE TITLE
Devise a better payload structure

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/announce-backend#3]
I'm not super pleased with how the `server` object looks right now. I'd like some way to distinguish between a server list object and a server details object.

The difference is that when querying a full list of servers (or page of servers, when that gets implemented) you only want to respond with the vital information - with the standard browser that's:
- password
- hostname
- player count
- player max
- gamemode
- language

Then, when you click a server that's when you get the richer information such as the rules, players and additional information such as a server banner image, a discord link, etc.

One solution I thought of was two structures, one for the "core" info and one for the "full" info:

```json
{
    "hn": "My cool server",
    "pc": 12,
    "pm": 32,
    "gm": "SS",
    "la": "English",
    "pa": false
}
```

```json
{
    "core": {
        "hn": "My cool server",
        "pc": 12,
        "pm": 32,
        "gm": "SS",
        "la": "English",
        "pa": false
    },
    "description": "this is the best server on the planet, be sure to join our discord!",
    "discord": "discord.me/greatest-samp-server-ever",
    "rules": { ... }.
    "players": [ ... ]
}
```

Where the "core" object is nested within the "full" object. This would allow services to query a specific server and get all the information they need, instantly while also being able to get efficiently sized lists of servers without the information they don't need right away.

The downside with this is complicating the POST for server announcements, if I do plan to put this into a Pawn script, the code is going to be a bit messy!

The other option is to bundle it all together into a single object and only send part of it when responding to a list request:

```json
{
    "hn": "My cool server",
    "pc": 12,
    "pm": 32,
    "gm": "SS",
    "la": "English",
    "pa": false
    "description": "this is the best server on the planet, be sure to join our discord!",
    "discord": "discord.me/greatest-samp-server-ever",
    "rules": { ... }.
    "players": [ ... ]
}
```

Which just feels like too much of a hack on what was quite a consistent API design.

Worth discussion before I make a decision for v1!

**Comment by BigETI** [comment]
Attributes should have proper names. "hn" -> "Hostname", "pc" -> "PlayerCount" and etc.
In NOTES.md there was this extension object structure for advanced information.

> Extended: This attribute is an object that cotains multiple attributes like for example website URL, contact email and etc.

**Comment by Southclaws** [comment]
The reason the names for those specific fields are short is to minimise network traffic for server list queries - inspired mostly by the JWT spec. The extra bytes would add up if the server listing kicks back 1000 servers per page (however, I haven't really thought a lot about paging yet).

If paging is a good enough solution, I suppose moving to more readable field names couldn't hurt.

**Comment by BigETI** [comment]
I am totally for paging to be honest.
