### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by typ431127** [Southclaws/announce-backend#32]
panic: required key SAMPLIST_BIND missing value

goroutine 1 [running]:
main.main()
	/data/go/src/samp-servers-api/main.go:16 +0x133
exit status 2

I also use the Dockerfile to build and compile locally.

**Comment by Southclaws** [comment]
`SAMPLIST_BIND` is an environment variable, there are a set of required envronment variables you can find here: https://github.com/Southclaws/samp-servers-api/blob/master/types/config.go

The format is simply upper-snake-case with `SAMPCTL_` as the prefix.
