### ISSUE TITLE
new server adding issue with api v2 and v3

### ISSUE THREAD

**Issue by vijayymmeena** [Southclaws/announce-backend#33]
**Query Posted to serve**r
   curl --request POST http://api.samp-servers.net/v2/server -d '13.59.61.92:7777'
    curl --request POST http://api.samp-servers.net/v2/server/13.59.61.92:7777

**Results** 
no address specifiedrequest address '172.30.0.5' does not match declared server address
or
address is empty

Solution required for adding new server on http://samp-servers.net.

**Comment by Southclaws** [comment]
Should be fixed now, thanks for reporting/testing!
