### ISSUE TITLE
Simplified POST option for servers

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/announce-backend#4]
This idea comes from messing with the UDP API which is now implemented and working.

To speed up onboarding of users, I think a nice simple HTTP POST request which simply contains an IP address could be nicer than utilising all the other features right off the bat.

This would allow users to either simply post their IP as a string to the `/server` endpoint or post nothing to the `/server/{ip}` endpoint - either way, maybe both?

```pawn
HTTP(0, HTTP_HEAD, "http://api.samp.southcla.ws/server", "192.168.1.1", "");
```
or
```pawn
HTTP(0, HTTP_HEAD, "http://api.samp.southcla.ws/server/192.168.1.1", "", ""); // obviously with a format() call in real life
```

This would then trigger the backend to perform UDP queries to gather the rest of the server information.

Then, in future the plugin can be advertised to users to enhance their server listing with additional features such as a banner image, a logo, a discord link and stuff like that.

**Comment by BigETI** [comment]
I have to agree that this is the most easiest way to achieve in PAWN.

**Comment by BigETI** [comment]
I have to add that a code page should be definable at POST to avoid mojibake for foreign code pages when using the SA:MP query mechanism.

**Comment by Southclaws** [comment]
- [x] Implement simplified endpoint
- [ ] Implement codepage option for endpoint
