### ISSUE TITLE
Website "add" button does not add the server

### ISSUE THREAD

**Issue by Sasino97** [Southclaws/announce-backend#54]
I tried adding my server address to samp-servers.net without success. I first used Microsoft Edge, then I retried with Google Chrome. In both cases my server was not added to the list.

**Comment by Southclaws** [comment]
Can you post the IP you attempted to add? I just tested the post and it returned a 200 Success response so the actual posting is working (Admitidly, it should provide some feedback but that's a frontend issue). The server listing engine is queue based and new additions are added to the end of the queue so it may take some time to be queried.

**Comment by Sasino97** [comment]
Sure; I tried to add my ip 217.61.0.193 (or sasinosoft.com), in both cases it was not added to the list; I tried to search it by its name using the search function.

**Comment by Southclaws** [comment]
It has been posted: https://samp-servers.net/server/217.61.0.193:7777

But this highlights another issue: since the IP was removed from the frontend internal list, the search doesn't work for IP addresses.

**Comment by Southclaws** [comment]
Closing and opening a new issue for frontend.
