### ISSUE TITLE
Implement server list pagination

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/announce-backend#7]
As the list grows, pagination will become a necessity to minimise network traffic. The key factors will be page size, rate limiting and caching.

**Comment by BigETI** [comment]
IP only requests should be non paged, where basic server list requests should have a "/{page number}", starting at 1 or revert to 1, if no page was defined in GET.

**Comment by Southclaws** [comment]
Implemented using a URL query field `page`, must be non-zero.
